<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>lemon 0717测试报告</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2.2"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    
<style type="text/css" media="screen">
body        { font-family: Microsoft YaHei,Tahoma,arial,helvetica,sans-serif;padding: 20px; font-size: 120%; }
table       { font-size: 100%; }
/* -- heading ---------------------------------------------------------------------- */
.heading {
    margin-top: 0ex;
    margin-bottom: 1ex;
}
.heading .description {
    margin-top: 4ex;
    margin-bottom: 6ex;
}
/* -- report ------------------------------------------------------------------------ */
#total_row  { font-weight: bold; }
.passCase   { color: #5cb85c; }
.failCase   { color: #d9534f; font-weight: bold; }
.errorCase  { color: #f0ad4e; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }
</style>

</head>
<body >
<script language="javascript" type="text/javascript">
output_list = Array();
/*level 调整增加只显示通过用例的分类 --Findyou
0:Summary //all hiddenRow
1:Failed  //pt hiddenRow, ft none
2:Pass    //pt none, ft hiddenRow
3:All     //pt none, ft none
*/
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level == 2 || level == 0 ) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level < 2) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
    }
    //加入【详细】切换文字变化 --Findyou
    detail_class=document.getElementsByClassName('detail');
	//console.log(detail_class.length)
	if (level == 3) {
		for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="收起"
		}
	}
	else{
			for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="详细"
		}
	}
}
function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {
        //ID修改 点 为 下划线 -Findyou
        tid0 = 't' + cid.substr(1) + '_' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];
        //修改点击无法收起的BUG，加入【详细】切换文字变化 --Findyou
        if (toHide) {
            document.getElementById(tid).className = 'hiddenRow';
            document.getElementById(cid).innerText = "详细"
        }
        else {
            document.getElementById(tid).className = '';
            document.getElementById(cid).innerText = "收起"
        }
    }
}
function html_escape(s) {
    s = s.replace(/&/g,'&amp;');
    s = s.replace(/</g,'&lt;');
    s = s.replace(/>/g,'&gt;');
    return s;
}
</script>
<div class='heading'>
<h1 style="font-family: Microsoft YaHei">lemon 0717测试报告</h1>
<p class='attribute'><strong>测试人员 : </strong> 最爱宝宝的Tuosang</p>
<p class='attribute'><strong>开始时间 : </strong> 2019-07-18 09:47:33</p>
<p class='attribute'><strong>合计耗时 : </strong> 0:00:02.370169</p>
<p class='attribute'><strong>测试结果 : </strong> 共 10，通过 4，失败 6，通过率= 40.00%</p>

<p class='description'>lemon 0717测试报告</p>
</div>


<p id='show_detail_line'>
<a class="btn btn-primary" href='javascript:showCase(0)'>概要{ 40.00% }</a>
<a class="btn btn-danger" href='javascript:showCase(1)'>失败{ 6 }</a>
<a class="btn btn-success" href='javascript:showCase(2)'>通过{ 4 }</a>
<a class="btn btn-info" href='javascript:showCase(3)'>所有{ 10 }</a>
</p>
<table id='result_table' class="table table-condensed table-bordered table-hover">
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row' class="text-center success" style="font-weight: bold;font-size: 16px;">
    <td>用例集/测试用例</td>
    <td>总计</td>
    <td>通过</td>
    <td>失败</td>
    <td>错误</td>
    <td>详细</td>
</tr>

<tr class='failClass warning'>
    <td>API_2.test_cases.test_cases.TestCases</td>
    <td class="text-center">10</td>
    <td class="text-center">4</td>
    <td class="text-center">6</td>
    <td class="text-center">0</td>
    <td class="text-center"><a href="javascript:showClassDetail('c1',10)" class="detail" id='c1'>详细</a></td>
</tr>

<tr id='pt1_1' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_cases_01</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt1_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt1_1'>通过</button>
    <div id='div_pt1_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt1_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt1_1'>通过</button>
    <div id='div_pt1_1' class="collapse in" align="left">
    <pre>
    
pt1_1: 2019-07-18 09:47:33,647-INFO-my_log.py-api-log-[日志信息]:------正在测试Register模里面第1条测试用例：正常注册
2019-07-18 09:47:33,648-INFO-my_log.py-api-log-[日志信息]:测试数据是：{'Params': "{'mobilephone':'18574379914','pwd':'123456','regname':'lemonchupan'}", 'Method': 'get', 'Title': '正常注册', 'Url': 'http://39.105.94.71:8080/futureloan/mvc/api/member/register', 'Module': 'Register', 'CaseId': 1, 'ExpectedResult': "{'msg': '手机号码已被注册', 'status': 0, 'data': None, 'code': '20110'}"}
2019-07-18 09:47:33,896-INFO-my_log.py-api-log-[日志信息]:实际结果为：{'msg': '手机号码已被注册', 'code': '20110', 'status': 0, 'data': None}


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_2' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_cases_02</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt1_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt1_2'>通过</button>
    <div id='div_pt1_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt1_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt1_2'>通过</button>
    <div id='div_pt1_2' class="collapse in" align="left">
    <pre>
    
pt1_2: 2019-07-18 09:47:33,897-INFO-my_log.py-api-log-[日志信息]:------正在测试Register模里面第2条测试用例：手机号为空
2019-07-18 09:47:33,899-INFO-my_log.py-api-log-[日志信息]:测试数据是：{'Params': "{'mobilephone':'','pwd':'123456','regname':'lemonchupan'}", 'Method': 'get', 'Title': '手机号为空', 'Url': 'http://39.105.94.71:8080/futureloan/mvc/api/member/register', 'Module': 'Register', 'CaseId': 2, 'ExpectedResult': "{'data': None, 'status': 0, 'code': '20103', 'msg': '手机号不能为空'}"}
2019-07-18 09:47:34,126-INFO-my_log.py-api-log-[日志信息]:实际结果为：{'msg': '手机号不能为空', 'code': '20103', 'status': 0, 'data': None}


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_3' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_cases_03</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt1_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt1_3'>通过</button>
    <div id='div_pt1_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt1_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt1_3'>通过</button>
    <div id='div_pt1_3' class="collapse in" align="left">
    <pre>
    
pt1_3: 2019-07-18 09:47:34,127-INFO-my_log.py-api-log-[日志信息]:------正在测试Register模里面第3条测试用例：密码长度小于6
2019-07-18 09:47:34,128-INFO-my_log.py-api-log-[日志信息]:测试数据是：{'Params': "{'mobilephone':'18574379913','pwd':'12345','regname':'lemonchupan'}", 'Method': 'post', 'Title': '密码长度小于6', 'Url': 'http://39.105.94.71:8080/futureloan/mvc/api/member/register', 'Module': 'Register', 'CaseId': 3, 'ExpectedResult': "{'status':0,'code':'20108','data': None,'msg':'密码长度必须为6~18'}"}
2019-07-18 09:47:34,349-INFO-my_log.py-api-log-[日志信息]:实际结果为：{'msg': '密码长度必须为6~18', 'code': '20108', 'status': 0, 'data': None}


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_4' class='none'>
    <td class='failCase'><div class='testcase'>test_cases_04</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_4'>失败</button>
    <div id='div_ft1_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_4'>失败</button>
    <div id='div_ft1_4' class="collapse in" align="left">
    <pre>
    
ft1_4: 2019-07-18 09:47:34,355-INFO-my_log.py-api-log-[日志信息]:------正在测试Register模里面第4条测试用例：手机号小于11位
2019-07-18 09:47:34,356-INFO-my_log.py-api-log-[日志信息]:测试数据是：{'Params': "{'mobilephone':'1857437993','pwd':'12345','regname':'lemonchupan'}", 'Method': 'post', 'Title': '手机号小于11位', 'Url': 'http://39.105.94.71:8080/futureloan/mvc/api/member/register', 'Module': 'Register', 'CaseId': 4, 'ExpectedResult': "{'status':0,'code':'20109','data': None,'msg':'手机号码格式不正确'}"}
2019-07-18 09:47:34,422-CRITICAL-my_log.py-api-log-[日志信息]:http请求出错了，错误是：{'msg': '手机号码格式不正确', 'code': '20109', 'status': 0, 'data': None} != {'msg': '密码长度必须为6~18', 'code': '20108', 'status': 0, 'data': None}
- {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?               ^                         ^^^ ^^^^^

+ {'code': '20108', 'data': None, 'msg': '密码长度必须为6~18', 'status': 0}
?               ^                         ^ ^^^^^^^^^

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\kilimall\PycharmProjects\untitled1\python lesson1\API_2\test_cases\test_cases.py", line 41, in test_cases
    raise e#处理完异常之后  不要留在家里 要抛出去
  File "C:\Users\kilimall\PycharmProjects\untitled1\python lesson1\API_2\test_cases\test_cases.py", line 36, in test_cases
    self.assertEqual(eval(case['ExpectedResult']),resp.json())#http发送请求拿到的实际返回结果
AssertionError: {'msg': '手机号码格式不正确', 'code': '20109', 'status': 0, 'data': None} != {'msg': '密码长度必须为6~18', 'code': '20108', 'status': 0, 'data': None}
- {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?               ^                         ^^^ ^^^^^

+ {'code': '20108', 'data': None, 'msg': '密码长度必须为6~18', 'status': 0}
?               ^                         ^ ^^^^^^^^^



    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_5' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_cases_05</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt1_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt1_5'>通过</button>
    <div id='div_pt1_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt1_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt1_5'>通过</button>
    <div id='div_pt1_5' class="collapse in" align="left">
    <pre>
    
pt1_5: 2019-07-18 09:47:34,587-INFO-my_log.py-api-log-[日志信息]:------正在测试Register模里面第5条测试用例：已注册手机号再次注册
2019-07-18 09:47:34,588-INFO-my_log.py-api-log-[日志信息]:测试数据是：{'Params': "{'mobilephone':'18574379913','pwd':'123456','regname':'lemonchupan'}", 'Method': 'post', 'Title': '已注册手机号再次注册', 'Url': 'http://39.105.94.71:8080/futureloan/mvc/api/member/register', 'Module': 'Register', 'CaseId': 5, 'ExpectedResult': "{'status':0,'code':'20110','data': None,'msg':'手机号码已被注册'}"}
2019-07-18 09:47:34,850-INFO-my_log.py-api-log-[日志信息]:实际结果为：{'msg': '手机号码已被注册', 'code': '20110', 'status': 0, 'data': None}


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_6' class='none'>
    <td class='failCase'><div class='testcase'>test_cases_06</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_6'>失败</button>
    <div id='div_ft1_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_6'>失败</button>
    <div id='div_ft1_6' class="collapse in" align="left">
    <pre>
    
ft1_6: 2019-07-18 09:47:34,854-INFO-my_log.py-api-log-[日志信息]:------正在测试login模里面第6条测试用例：正常登陆
2019-07-18 09:47:34,857-INFO-my_log.py-api-log-[日志信息]:测试数据是：{'Params': "{'mobilephone':'18574379913','pwd':'123456'}", 'Method': 'post', 'Title': '正常登陆', 'Url': 'http://39.105.94.71:8080/futureloan/mvc/api/member/login', 'Module': 'login', 'CaseId': 6, 'ExpectedResult': "{'status':1,'code':'10001','data': None,'msg':'成功'}"}
2019-07-18 09:47:34,920-CRITICAL-my_log.py-api-log-[日志信息]:http请求出错了，错误是：{'msg': '成功', 'code': '10001', 'status': 1, 'data': None} != {'msg': '登录成功', 'code': '10001', 'status': 1, 'data': None}
- {'code': '10001', 'data': None, 'msg': '成功', 'status': 1}
+ {'code': '10001', 'data': None, 'msg': '登录成功', 'status': 1}
?                                         ++

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\kilimall\PycharmProjects\untitled1\python lesson1\API_2\test_cases\test_cases.py", line 41, in test_cases
    raise e#处理完异常之后  不要留在家里 要抛出去
  File "C:\Users\kilimall\PycharmProjects\untitled1\python lesson1\API_2\test_cases\test_cases.py", line 36, in test_cases
    self.assertEqual(eval(case['ExpectedResult']),resp.json())#http发送请求拿到的实际返回结果
AssertionError: {'msg': '成功', 'code': '10001', 'status': 1, 'data': None} != {'msg': '登录成功', 'code': '10001', 'status': 1, 'data': None}
- {'code': '10001', 'data': None, 'msg': '成功', 'status': 1}
+ {'code': '10001', 'data': None, 'msg': '登录成功', 'status': 1}
?                                         ++



    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_7' class='none'>
    <td class='failCase'><div class='testcase'>test_cases_07</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_7'>失败</button>
    <div id='div_ft1_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_7'>失败</button>
    <div id='div_ft1_7' class="collapse in" align="left">
    <pre>
    
ft1_7: 2019-07-18 09:47:35,080-INFO-my_log.py-api-log-[日志信息]:------正在测试login模里面第7条测试用例：用户名输入为空
2019-07-18 09:47:35,081-INFO-my_log.py-api-log-[日志信息]:测试数据是：{'Params': "{'mobilephone':'','pwd':'123456'}", 'Method': 'post', 'Title': '用户名输入为空', 'Url': 'http://39.105.94.71:8080/futureloan/mvc/api/member/login', 'Module': 'login', 'CaseId': 7, 'ExpectedResult': "{'status':0,'code':'20103','data': None,'msg':'参数错误：参数不能为空'}"}
2019-07-18 09:47:35,148-CRITICAL-my_log.py-api-log-[日志信息]:http请求出错了，错误是：{'msg': '参数错误：参数不能为空', 'code': '20103', 'status': 0, 'data': None} != {'msg': '手机号不能为空', 'code': '20103', 'status': 0, 'data': None}
- {'code': '20103', 'data': None, 'msg': '参数错误：参数不能为空', 'status': 0}
?                                         ^^^^^^^

+ {'code': '20103', 'data': None, 'msg': '手机号不能为空', 'status': 0}
?                                         ^^^

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\kilimall\PycharmProjects\untitled1\python lesson1\API_2\test_cases\test_cases.py", line 41, in test_cases
    raise e#处理完异常之后  不要留在家里 要抛出去
  File "C:\Users\kilimall\PycharmProjects\untitled1\python lesson1\API_2\test_cases\test_cases.py", line 36, in test_cases
    self.assertEqual(eval(case['ExpectedResult']),resp.json())#http发送请求拿到的实际返回结果
AssertionError: {'msg': '参数错误：参数不能为空', 'code': '20103', 'status': 0, 'data': None} != {'msg': '手机号不能为空', 'code': '20103', 'status': 0, 'data': None}
- {'code': '20103', 'data': None, 'msg': '参数错误：参数不能为空', 'status': 0}
?                                         ^^^^^^^

+ {'code': '20103', 'data': None, 'msg': '手机号不能为空', 'status': 0}
?                                         ^^^



    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_8' class='none'>
    <td class='failCase'><div class='testcase'>test_cases_08</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_8' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_8'>失败</button>
    <div id='div_ft1_8' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_8' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_8'>失败</button>
    <div id='div_ft1_8' class="collapse in" align="left">
    <pre>
    
ft1_8: 2019-07-18 09:47:35,314-INFO-my_log.py-api-log-[日志信息]:------正在测试login模里面第8条测试用例：密码输入为空
2019-07-18 09:47:35,315-INFO-my_log.py-api-log-[日志信息]:测试数据是：{'Params': "{'mobilephone':'18574379913','pwd':''}", 'Method': 'post', 'Title': '密码输入为空', 'Url': 'http://39.105.94.71:8080/futureloan/mvc/api/member/login', 'Module': 'login', 'CaseId': 8, 'ExpectedResult': "{'status':0,'code':'20103','data': None,'msg':'参数错误：参数不能为空'}"}
2019-07-18 09:47:35,379-CRITICAL-my_log.py-api-log-[日志信息]:http请求出错了，错误是：{'msg': '参数错误：参数不能为空', 'code': '20103', 'status': 0, 'data': None} != {'msg': '密码不能为空', 'code': '20103', 'status': 0, 'data': None}
- {'code': '20103', 'data': None, 'msg': '参数错误：参数不能为空', 'status': 0}
?                                         ^^^^^^^

+ {'code': '20103', 'data': None, 'msg': '密码不能为空', 'status': 0}
?                                         ^^

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\kilimall\PycharmProjects\untitled1\python lesson1\API_2\test_cases\test_cases.py", line 41, in test_cases
    raise e#处理完异常之后  不要留在家里 要抛出去
  File "C:\Users\kilimall\PycharmProjects\untitled1\python lesson1\API_2\test_cases\test_cases.py", line 36, in test_cases
    self.assertEqual(eval(case['ExpectedResult']),resp.json())#http发送请求拿到的实际返回结果
AssertionError: {'msg': '参数错误：参数不能为空', 'code': '20103', 'status': 0, 'data': None} != {'msg': '密码不能为空', 'code': '20103', 'status': 0, 'data': None}
- {'code': '20103', 'data': None, 'msg': '参数错误：参数不能为空', 'status': 0}
?                                         ^^^^^^^

+ {'code': '20103', 'data': None, 'msg': '密码不能为空', 'status': 0}
?                                         ^^



    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_9' class='none'>
    <td class='failCase'><div class='testcase'>test_cases_09</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_9' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_9'>失败</button>
    <div id='div_ft1_9' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_9' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_9'>失败</button>
    <div id='div_ft1_9' class="collapse in" align="left">
    <pre>
    
ft1_9: 2019-07-18 09:47:35,547-INFO-my_log.py-api-log-[日志信息]:------正在测试login模里面第9条测试用例：正确的用户名，对应密码错误
2019-07-18 09:47:35,548-INFO-my_log.py-api-log-[日志信息]:测试数据是：{'Params': "{'mobilephone':'18574379913','pwd':'1234567'}", 'Method': 'post', 'Title': '正确的用户名，对应密码错误', 'Url': 'http://39.105.94.71:8080/futureloan/mvc/api/member/login', 'Module': 'login', 'CaseId': 9, 'ExpectedResult': "{'status':0,'code':'20111','data': None,'msg':'用户名或者密码错误'}"}
2019-07-18 09:47:35,623-CRITICAL-my_log.py-api-log-[日志信息]:http请求出错了，错误是：{'msg': '用户名或者密码错误', 'code': '20111', 'status': 0, 'data': None} != {'msg': '用户名或密码错误', 'code': '20111', 'status': 0, 'data': None}
- {'code': '20111', 'data': None, 'msg': '用户名或者密码错误', 'status': 0}
?                                             -

+ {'code': '20111', 'data': None, 'msg': '用户名或密码错误', 'status': 0}
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\kilimall\PycharmProjects\untitled1\python lesson1\API_2\test_cases\test_cases.py", line 41, in test_cases
    raise e#处理完异常之后  不要留在家里 要抛出去
  File "C:\Users\kilimall\PycharmProjects\untitled1\python lesson1\API_2\test_cases\test_cases.py", line 36, in test_cases
    self.assertEqual(eval(case['ExpectedResult']),resp.json())#http发送请求拿到的实际返回结果
AssertionError: {'msg': '用户名或者密码错误', 'code': '20111', 'status': 0, 'data': None} != {'msg': '用户名或密码错误', 'code': '20111', 'status': 0, 'data': None}
- {'code': '20111', 'data': None, 'msg': '用户名或者密码错误', 'status': 0}
?                                             -

+ {'code': '20111', 'data': None, 'msg': '用户名或密码错误', 'status': 0}


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_10' class='none'>
    <td class='failCase'><div class='testcase'>test_cases_10</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_10' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_10'>失败</button>
    <div id='div_ft1_10' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_10' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_10'>失败</button>
    <div id='div_ft1_10' class="collapse in" align="left">
    <pre>
    
ft1_10: 2019-07-18 09:47:35,790-INFO-my_log.py-api-log-[日志信息]:------正在测试login模里面第10条测试用例：未注册手机号登陆
2019-07-18 09:47:35,792-INFO-my_log.py-api-log-[日志信息]:测试数据是：{'Params': "{'mobilephone':'13786268722','pwd':'123457'}", 'Method': 'get', 'Title': '未注册手机号登陆', 'Url': 'http://39.105.94.71:8080/futureloan/mvc/api/member/login', 'Module': 'login', 'CaseId': 10, 'ExpectedResult': "{'status':0,'code':'20111','data': None,'msg':'用户名或者密码错误'}"}
2019-07-18 09:47:35,860-CRITICAL-my_log.py-api-log-[日志信息]:http请求出错了，错误是：{'msg': '用户名或者密码错误', 'code': '20111', 'status': 0, 'data': None} != {'msg': '用户名或密码错误', 'code': '20111', 'status': 0, 'data': None}
- {'code': '20111', 'data': None, 'msg': '用户名或者密码错误', 'status': 0}
?                                             -

+ {'code': '20111', 'data': None, 'msg': '用户名或密码错误', 'status': 0}
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\kilimall\PycharmProjects\untitled1\python lesson1\API_2\test_cases\test_cases.py", line 41, in test_cases
    raise e#处理完异常之后  不要留在家里 要抛出去
  File "C:\Users\kilimall\PycharmProjects\untitled1\python lesson1\API_2\test_cases\test_cases.py", line 36, in test_cases
    self.assertEqual(eval(case['ExpectedResult']),resp.json())#http发送请求拿到的实际返回结果
AssertionError: {'msg': '用户名或者密码错误', 'code': '20111', 'status': 0, 'data': None} != {'msg': '用户名或密码错误', 'code': '20111', 'status': 0, 'data': None}
- {'code': '20111', 'data': None, 'msg': '用户名或者密码错误', 'status': 0}
?                                             -

+ {'code': '20111', 'data': None, 'msg': '用户名或密码错误', 'status': 0}


    </pre>
    </div>
    </td>
</tr>

<tr id='total_row' class="text-center active">
    <td>总计</td>
    <td>10</td>
    <td>4</td>
    <td>6</td>
    <td>0</td>
    <td>通过率：40.00%</td>
</tr>
</table>

<div id='ending'>&nbsp;</div>
    <div style=" position:fixed;right:50px; bottom:30px; width:20px; height:20px;cursor:pointer">
    <a href="#"><span class="glyphicon glyphicon-eject" style = "font-size:30px;" aria-hidden="true">
    </span></a></div>
    
</body>
</html>
